# Generated by Django 3.1.1 on 2020-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0005_auto_20200905_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='defaulf.jpg', upload_to='item_pics'),
        ),
    ]
